### ISSUE TITLE
Why would I need this action?

### ISSUE THREAD

**Issue by airtonix** [squash-commit-app/squash-commit-app#17]
There's very little documentation and the description while it explains what it does, still leaves me confused as to why it does this.

**Comment by oscard0m** [comment]
Hi @airtonix!

You are right, I think this app needs more details on the reason why it exists.

Given a Pull Request, if it only has one commit, when you try to _squash-and-merge_, the default message used for that squashed commit will be the commit message of that single commit instead of the Pull Request title.

Sometimes this is not the desired behavior (when you want to use conventional commits for example). When a PR has 2 or more commits, GitHub uses the PR title, so the goal of this GitHub App is to enforce using the PR title as a commit message when doing a _squash-and-merge_.

You can find more context here: https://twitter.com/gr2m/status/1449069394156408834?s=20&t=aeZ1WG4ltHpPZk7QeF4yzw

---

Recently, GitHub released an option to do that so this App is not necessary anymore: https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
